title: Gyudon
author: Grace Yu
description: cats are great
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
permalink: /:title/

theme: 'tufte-pandoc-jekyll'

permalink: '/:categories/:slug/'

markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+smart+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'

header_includes:
  - '<link rel="icon" sizes="16x16" href="/assets/images/favicon.ico">'
  - '<link rel="stylesheet" href="/assets/css/extras.css">'

gems:
  - jekyll-feed
  - jekyll-pandoc
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - tags
